//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/10/2016 7:50:42 PM
namespace ApiClient.ApiDataSvcDemo
{
    /// <summary>
    /// There are no comments for ProductSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ProductSingle")]
    public partial class ProductSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Product>
    {
        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProductSingle object.
        /// </summary>
        public ProductSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Product> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for ProductCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategory")]
        public global::ApiClient.ApiDataSvcDemo.ProductCategorySingle ProductCategory
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ProductCategory == null))
                {
                    this._ProductCategory = new global::ApiClient.ApiDataSvcDemo.ProductCategorySingle(this.Context, GetPath("ProductCategory"));
                }
                return this._ProductCategory;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ApiClient.ApiDataSvcDemo.ProductCategorySingle _ProductCategory;
    }
    /// <summary>
    /// There are no comments for Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ProductID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Product")]
    public partial class Product : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="productNumber">Initial value of ProductNumber.</param>
        /// <param name="standardCost">Initial value of StandardCost.</param>
        /// <param name="listPrice">Initial value of ListPrice.</param>
        /// <param name="sellStartDate">Initial value of SellStartDate.</param>
        /// <param name="rowguid">Initial value of Rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Product CreateProduct(int productID, 
                    string name, 
                    string productNumber, 
                    decimal standardCost, 
                    decimal listPrice, 
                    global::System.DateTimeOffset sellStartDate, 
                    global::System.Guid rowguid, 
                    global::System.DateTimeOffset modifiedDate)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.Name = name;
            product.ProductNumber = productNumber;
            product.StandardCost = standardCost;
            product.ListPrice = listPrice;
            product.SellStartDate = sellStartDate;
            product.Rowguid = rowguid;
            product.ModifiedDate = modifiedDate;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductID")]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
                this.OnPropertyChanged("ProductID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ProductNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductNumber")]
        public string ProductNumber
        {
            get
            {
                return this._ProductNumber;
            }
            set
            {
                this.OnProductNumberChanging(value);
                this._ProductNumber = value;
                this.OnProductNumberChanged();
                this.OnPropertyChanged("ProductNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ProductNumber;
        partial void OnProductNumberChanging(string value);
        partial void OnProductNumberChanged();
        /// <summary>
        /// There are no comments for Property Color in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Color")]
        public string Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this.OnColorChanging(value);
                this._Color = value;
                this.OnColorChanged();
                this.OnPropertyChanged("Color");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Color;
        partial void OnColorChanging(string value);
        partial void OnColorChanged();
        /// <summary>
        /// There are no comments for Property StandardCost in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StandardCost")]
        public decimal StandardCost
        {
            get
            {
                return this._StandardCost;
            }
            set
            {
                this.OnStandardCostChanging(value);
                this._StandardCost = value;
                this.OnStandardCostChanged();
                this.OnPropertyChanged("StandardCost");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _StandardCost;
        partial void OnStandardCostChanging(decimal value);
        partial void OnStandardCostChanged();
        /// <summary>
        /// There are no comments for Property ListPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ListPrice")]
        public decimal ListPrice
        {
            get
            {
                return this._ListPrice;
            }
            set
            {
                this.OnListPriceChanging(value);
                this._ListPrice = value;
                this.OnListPriceChanged();
                this.OnPropertyChanged("ListPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _ListPrice;
        partial void OnListPriceChanging(decimal value);
        partial void OnListPriceChanged();
        /// <summary>
        /// There are no comments for Property Size in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Size")]
        public string Size
        {
            get
            {
                return this._Size;
            }
            set
            {
                this.OnSizeChanging(value);
                this._Size = value;
                this.OnSizeChanged();
                this.OnPropertyChanged("Size");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Size;
        partial void OnSizeChanging(string value);
        partial void OnSizeChanged();
        /// <summary>
        /// There are no comments for Property Weight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Weight")]
        public global::System.Nullable<decimal> Weight
        {
            get
            {
                return this._Weight;
            }
            set
            {
                this.OnWeightChanging(value);
                this._Weight = value;
                this.OnWeightChanged();
                this.OnPropertyChanged("Weight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<decimal> _Weight;
        partial void OnWeightChanging(global::System.Nullable<decimal> value);
        partial void OnWeightChanged();
        /// <summary>
        /// There are no comments for Property ProductCategoryID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategoryID")]
        public global::System.Nullable<int> ProductCategoryID
        {
            get
            {
                return this._ProductCategoryID;
            }
            set
            {
                this.OnProductCategoryIDChanging(value);
                this._ProductCategoryID = value;
                this.OnProductCategoryIDChanged();
                this.OnPropertyChanged("ProductCategoryID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _ProductCategoryID;
        partial void OnProductCategoryIDChanging(global::System.Nullable<int> value);
        partial void OnProductCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ProductModelID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductModelID")]
        public global::System.Nullable<int> ProductModelID
        {
            get
            {
                return this._ProductModelID;
            }
            set
            {
                this.OnProductModelIDChanging(value);
                this._ProductModelID = value;
                this.OnProductModelIDChanged();
                this.OnPropertyChanged("ProductModelID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _ProductModelID;
        partial void OnProductModelIDChanging(global::System.Nullable<int> value);
        partial void OnProductModelIDChanged();
        /// <summary>
        /// There are no comments for Property SellStartDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SellStartDate")]
        public global::System.DateTimeOffset SellStartDate
        {
            get
            {
                return this._SellStartDate;
            }
            set
            {
                this.OnSellStartDateChanging(value);
                this._SellStartDate = value;
                this.OnSellStartDateChanged();
                this.OnPropertyChanged("SellStartDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _SellStartDate;
        partial void OnSellStartDateChanging(global::System.DateTimeOffset value);
        partial void OnSellStartDateChanged();
        /// <summary>
        /// There are no comments for Property SellEndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SellEndDate")]
        public global::System.Nullable<global::System.DateTimeOffset> SellEndDate
        {
            get
            {
                return this._SellEndDate;
            }
            set
            {
                this.OnSellEndDateChanging(value);
                this._SellEndDate = value;
                this.OnSellEndDateChanged();
                this.OnPropertyChanged("SellEndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _SellEndDate;
        partial void OnSellEndDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnSellEndDateChanged();
        /// <summary>
        /// There are no comments for Property DiscontinuedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DiscontinuedDate")]
        public global::System.Nullable<global::System.DateTimeOffset> DiscontinuedDate
        {
            get
            {
                return this._DiscontinuedDate;
            }
            set
            {
                this.OnDiscontinuedDateChanging(value);
                this._DiscontinuedDate = value;
                this.OnDiscontinuedDateChanged();
                this.OnPropertyChanged("DiscontinuedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DiscontinuedDate;
        partial void OnDiscontinuedDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDiscontinuedDateChanged();
        /// <summary>
        /// There are no comments for Property ThumbNailPhoto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ThumbNailPhoto")]
        public byte[] ThumbNailPhoto
        {
            get
            {
                return this._ThumbNailPhoto;
            }
            set
            {
                this.OnThumbNailPhotoChanging(value);
                this._ThumbNailPhoto = value;
                this.OnThumbNailPhotoChanged();
                this.OnPropertyChanged("ThumbNailPhoto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte[] _ThumbNailPhoto;
        partial void OnThumbNailPhotoChanging(byte[] value);
        partial void OnThumbNailPhotoChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailPhotoFileName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ThumbnailPhotoFileName")]
        public string ThumbnailPhotoFileName
        {
            get
            {
                return this._ThumbnailPhotoFileName;
            }
            set
            {
                this.OnThumbnailPhotoFileNameChanging(value);
                this._ThumbnailPhotoFileName = value;
                this.OnThumbnailPhotoFileNameChanged();
                this.OnPropertyChanged("ThumbnailPhotoFileName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ThumbnailPhotoFileName;
        partial void OnThumbnailPhotoFileNameChanging(string value);
        partial void OnThumbnailPhotoFileNameChanged();
        /// <summary>
        /// There are no comments for Property Rowguid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("rowguid")]
        public global::System.Guid Rowguid
        {
            get
            {
                return this._Rowguid;
            }
            set
            {
                this.OnRowguidChanging(value);
                this._Rowguid = value;
                this.OnRowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Rowguid;
        partial void OnRowguidChanging(global::System.Guid value);
        partial void OnRowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedDate")]
        public global::System.DateTimeOffset ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTimeOffset value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ProductCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategory")]
        public global::ApiClient.ApiDataSvcDemo.ProductCategory ProductCategory
        {
            get
            {
                return this._ProductCategory;
            }
            set
            {
                this.OnProductCategoryChanging(value);
                this._ProductCategory = value;
                this.OnProductCategoryChanged();
                this.OnPropertyChanged("ProductCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ApiClient.ApiDataSvcDemo.ProductCategory _ProductCategory;
        partial void OnProductCategoryChanging(global::ApiClient.ApiDataSvcDemo.ProductCategory value);
        partial void OnProductCategoryChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ProductCategorySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategorySingle")]
    public partial class ProductCategorySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ProductCategory>
    {
        /// <summary>
        /// Initialize a new ProductCategorySingle object.
        /// </summary>
        public ProductCategorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductCategorySingle object.
        /// </summary>
        public ProductCategorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProductCategorySingle object.
        /// </summary>
        public ProductCategorySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ProductCategory> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Products")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.Product> Products
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Products == null))
                {
                    this._Products = Context.CreateQuery<global::ApiClient.ApiDataSvcDemo.Product>(GetPath("Products"));
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.Product> _Products;
        /// <summary>
        /// There are no comments for ProductCategory1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategory1")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.ProductCategory> ProductCategory1
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ProductCategory1 == null))
                {
                    this._ProductCategory1 = Context.CreateQuery<global::ApiClient.ApiDataSvcDemo.ProductCategory>(GetPath("ProductCategory1"));
                }
                return this._ProductCategory1;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.ProductCategory> _ProductCategory1;
        /// <summary>
        /// There are no comments for ProductCategory2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategory2")]
        public global::ApiClient.ApiDataSvcDemo.ProductCategorySingle ProductCategory2
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ProductCategory2 == null))
                {
                    this._ProductCategory2 = new global::ApiClient.ApiDataSvcDemo.ProductCategorySingle(this.Context, GetPath("ProductCategory2"));
                }
                return this._ProductCategory2;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ApiClient.ApiDataSvcDemo.ProductCategorySingle _ProductCategory2;
    }
    /// <summary>
    /// There are no comments for ProductCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductCategoryID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ProductCategoryID")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategory")]
    public partial class ProductCategory : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ProductCategory object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="rowguid">Initial value of Rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ProductCategory CreateProductCategory(string name, global::System.Guid rowguid, global::System.DateTimeOffset modifiedDate)
        {
            ProductCategory productCategory = new ProductCategory();
            productCategory.Name = name;
            productCategory.Rowguid = rowguid;
            productCategory.ModifiedDate = modifiedDate;
            return productCategory;
        }
        /// <summary>
        /// There are no comments for Property ProductCategoryID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategoryID")]
        public global::System.Nullable<int> ProductCategoryID
        {
            get
            {
                return this._ProductCategoryID;
            }
            set
            {
                this.OnProductCategoryIDChanging(value);
                this._ProductCategoryID = value;
                this.OnProductCategoryIDChanged();
                this.OnPropertyChanged("ProductCategoryID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _ProductCategoryID;
        partial void OnProductCategoryIDChanging(global::System.Nullable<int> value);
        partial void OnProductCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ParentProductCategoryID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ParentProductCategoryID")]
        public global::System.Nullable<int> ParentProductCategoryID
        {
            get
            {
                return this._ParentProductCategoryID;
            }
            set
            {
                this.OnParentProductCategoryIDChanging(value);
                this._ParentProductCategoryID = value;
                this.OnParentProductCategoryIDChanged();
                this.OnPropertyChanged("ParentProductCategoryID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _ParentProductCategoryID;
        partial void OnParentProductCategoryIDChanging(global::System.Nullable<int> value);
        partial void OnParentProductCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Rowguid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("rowguid")]
        public global::System.Guid Rowguid
        {
            get
            {
                return this._Rowguid;
            }
            set
            {
                this.OnRowguidChanging(value);
                this._Rowguid = value;
                this.OnRowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Rowguid;
        partial void OnRowguidChanging(global::System.Guid value);
        partial void OnRowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedDate")]
        public global::System.DateTimeOffset ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTimeOffset value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Products")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ApiClient.ApiDataSvcDemo.Product> Products
        {
            get
            {
                return this._Products;
            }
            set
            {
                this.OnProductsChanging(value);
                this._Products = value;
                this.OnProductsChanged();
                this.OnPropertyChanged("Products");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ApiClient.ApiDataSvcDemo.Product> _Products = new global::Microsoft.OData.Client.DataServiceCollection<global::ApiClient.ApiDataSvcDemo.Product>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnProductsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ApiClient.ApiDataSvcDemo.Product> value);
        partial void OnProductsChanged();
        /// <summary>
        /// There are no comments for Property ProductCategory1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategory1")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ApiClient.ApiDataSvcDemo.ProductCategory> ProductCategory1
        {
            get
            {
                return this._ProductCategory1;
            }
            set
            {
                this.OnProductCategory1Changing(value);
                this._ProductCategory1 = value;
                this.OnProductCategory1Changed();
                this.OnPropertyChanged("ProductCategory1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ApiClient.ApiDataSvcDemo.ProductCategory> _ProductCategory1 = new global::Microsoft.OData.Client.DataServiceCollection<global::ApiClient.ApiDataSvcDemo.ProductCategory>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnProductCategory1Changing(global::Microsoft.OData.Client.DataServiceCollection<global::ApiClient.ApiDataSvcDemo.ProductCategory> value);
        partial void OnProductCategory1Changed();
        /// <summary>
        /// There are no comments for Property ProductCategory2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategory2")]
        public global::ApiClient.ApiDataSvcDemo.ProductCategory ProductCategory2
        {
            get
            {
                return this._ProductCategory2;
            }
            set
            {
                this.OnProductCategory2Changing(value);
                this._ProductCategory2 = value;
                this.OnProductCategory2Changed();
                this.OnPropertyChanged("ProductCategory2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ApiClient.ApiDataSvcDemo.ProductCategory _ProductCategory2;
        partial void OnProductCategory2Changing(global::ApiClient.ApiDataSvcDemo.ProductCategory value);
        partial void OnProductCategory2Changed();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ApiClient.ApiDataSvcDemo.Product as global::ApiClient.ApiDataSvcDemo.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ApiClient.ApiDataSvcDemo.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.Product> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ApiClient.ApiDataSvcDemo.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ApiClient.ApiDataSvcDemo.Product as global::ApiClient.ApiDataSvcDemo.ProductSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="productID">The value of productID</param>
        public static global::ApiClient.ApiDataSvcDemo.ProductSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.Product> source,
            int productID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ProductID", productID }
            };
            return new global::ApiClient.ApiDataSvcDemo.ProductSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ApiClient.ApiDataSvcDemo.ProductCategory as global::ApiClient.ApiDataSvcDemo.ProductCategorySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ApiClient.ApiDataSvcDemo.ProductCategorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.ProductCategory> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ApiClient.ApiDataSvcDemo.ProductCategorySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ApiClient.ApiDataSvcDemo.ProductCategory as global::ApiClient.ApiDataSvcDemo.ProductCategorySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="productCategoryID">The value of productCategoryID</param>
        public static global::ApiClient.ApiDataSvcDemo.ProductCategorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.ProductCategory> source,
            global::System.Nullable<int> productCategoryID)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ProductCategoryID", productCategoryID }
            };
            return new global::ApiClient.ApiDataSvcDemo.ProductCategorySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace ApiClient.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ApiDataSvcDemo", "ApiClient.ApiDataSvcDemo");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "ApiClient.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("ApiClient.ApiDataSvcDemo", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ApiDataSvcDemo.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ApiDataSvcDemo.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ApiClient.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Products")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<global::ApiClient.ApiDataSvcDemo.Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.Product> _Products;
        /// <summary>
        /// There are no comments for ProductCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductCategories")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.ProductCategory> ProductCategories
        {
            get
            {
                if ((this._ProductCategories == null))
                {
                    this._ProductCategories = base.CreateQuery<global::ApiClient.ApiDataSvcDemo.ProductCategory>("ProductCategories");
                }
                return this._ProductCategories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ApiClient.ApiDataSvcDemo.ProductCategory> _ProductCategories;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToProducts(global::ApiClient.ApiDataSvcDemo.Product product)
        {
            base.AddObject("Products", product);
        }
        /// <summary>
        /// There are no comments for ProductCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToProductCategories(global::ApiClient.ApiDataSvcDemo.ProductCategory productCategory)
        {
            base.AddObject("ProductCategories", productCategory);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""ApiDataSvcDemo"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Product"">
        <Key>
          <PropertyRef Name=""ProductID"" />
        </Key>
        <Property Name=""ProductID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""ProductNumber"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Color"" Type=""Edm.String"" />
        <Property Name=""StandardCost"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""ListPrice"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""Size"" Type=""Edm.String"" />
        <Property Name=""Weight"" Type=""Edm.Decimal"" />
        <Property Name=""ProductCategoryID"" Type=""Edm.Int32"" />
        <Property Name=""ProductModelID"" Type=""Edm.Int32"" />
        <Property Name=""SellStartDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""SellEndDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""DiscontinuedDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""ThumbNailPhoto"" Type=""Edm.Binary"" />
        <Property Name=""ThumbnailPhotoFileName"" Type=""Edm.String"" />
        <Property Name=""rowguid"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""ModifiedDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <NavigationProperty Name=""ProductCategory"" Type=""ApiDataSvcDemo.ProductCategory"">
          <ReferentialConstraint Property=""ProductCategoryID"" ReferencedProperty=""ProductCategoryID"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""ProductCategory"">
        <Key>
          <PropertyRef Name=""ProductCategoryID"" />
        </Key>
        <Property Name=""ProductCategoryID"" Type=""Edm.Int32"" />
        <Property Name=""ParentProductCategoryID"" Type=""Edm.Int32"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""rowguid"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""ModifiedDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <NavigationProperty Name=""Products"" Type=""Collection(ApiDataSvcDemo.Product)"" />
        <NavigationProperty Name=""ProductCategory1"" Type=""Collection(ApiDataSvcDemo.ProductCategory)"" />
        <NavigationProperty Name=""ProductCategory2"" Type=""ApiDataSvcDemo.ProductCategory"">
          <ReferentialConstraint Property=""ProductCategoryID"" ReferencedProperty=""ProductCategoryID"" />
        </NavigationProperty>
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Products"" EntityType=""ApiDataSvcDemo.Product"">
          <NavigationPropertyBinding Path=""ProductCategory"" Target=""ProductCategories"" />
        </EntitySet>
        <EntitySet Name=""ProductCategories"" EntityType=""ApiDataSvcDemo.ProductCategory"">
          <NavigationPropertyBinding Path=""Products"" Target=""Products"" />
          <NavigationPropertyBinding Path=""ProductCategory1"" Target=""ProductCategories"" />
          <NavigationPropertyBinding Path=""ProductCategory2"" Target=""ProductCategories"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
